config/routes.rb
Rails.application.routes.draw do
  resources :planner_notes
  resources :students
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/planner_note.rb
class PlannerNote < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:course_name, :teacher, :start_time, :end_time)
    end
end

app/controllers/planner_notes_controller.rb
class PlannerNotesController < ApplicationController
  before_action :set_planner_note, only: %i[ show edit update destroy ]

  # GET /planner_notes or /planner_notes.json
  def index
    @planner_notes = PlannerNote.all
  end

  # GET /planner_notes/1 or /planner_notes/1.json
  def show
  end

  # GET /planner_notes/new
  def new
    @planner_note = PlannerNote.new
  end

  # GET /planner_notes/1/edit
  def edit
  end

  # POST /planner_notes or /planner_notes.json
  def create
    @planner_note = PlannerNote.new(planner_note_params)

    respond_to do |format|
      if @planner_note.save
        format.html { redirect_to planner_note_url(@planner_note), notice: "Planner note was successfully created." }
        format.json { render :show, status: :created, location: @planner_note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @planner_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planner_notes/1 or /planner_notes/1.json
  def update
    respond_to do |format|
      if @planner_note.update(planner_note_params)
        format.html { redirect_to planner_note_url(@planner_note), notice: "Planner note was successfully updated." }
        format.json { render :show, status: :ok, location: @planner_note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @planner_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planner_notes/1 or /planner_notes/1.json
  def destroy
    @planner_note.destroy

    respond_to do |format|
      format.html { redirect_to planner_notes_url, notice: "Planner note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planner_note
      @planner_note = PlannerNote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def planner_note_params
      params.require(:planner_note).permit(:todo_date, :title, :details, :student_id, :course_id, :workflow_state)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :id_number, :date_of_birth, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/planner_notes_helper.rb
module PlannerNotesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">

  <p>
    <strong>Course id:</strong>
    <%= course.id %>
  </p>

  <p>
    <strong>Course name:</strong>
    <%= course.course_name %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= course.teacher %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= course.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= course.end_time %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :course_name, style: "display: block" %>
    <%= form.text_field :course_name %>
  </div>

  <div>
    <%= form.label :teacher, style: "display: block" %>
    <%= form.text_field :teacher %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.time_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.time_field :end_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", course %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planner_notes/_form.html.erb
<%= form_with(model: planner_note) do |form| %>
  <% if planner_note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(planner_note.errors.count, "error") %> prohibited this planner_note from being saved:</h2>

      <ul>
        <% planner_note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :todo_date, style: "display: block" %>
    <%= form.datetime_field :todo_date %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.label :workflow_state, style: "display: block" %>
    <%= form.text_field :workflow_state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/planner_notes/_planner_note.html.erb
<div id="<%= dom_id planner_note %>">
  <p>
    <strong>Todo date:</strong>
    <%= planner_note.todo_date %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= planner_note.title %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= planner_note.details %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= planner_note.student_id %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= planner_note.course_id %>
  </p>

  <p>
    <strong>Workflow state:</strong>
    <%= planner_note.workflow_state %>
  </p>

</div>

app/views/planner_notes/edit.html.erb
<h1>Editing planner note</h1>

<%= render "form", planner_note: @planner_note %>

<br>

<div>
  <%= link_to "Show this planner note", @planner_note %> |
  <%= link_to "Back to planner notes", planner_notes_path %>
</div>

app/views/planner_notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Planner notes</h1>

<div id="planner_notes">
  <% @planner_notes.each do |planner_note| %>
    <%= render planner_note %>
    <p>
      <%= link_to "Show this planner note", planner_note %>
    </p>
  <% end %>
</div>

<%= link_to "New planner note", new_planner_note_path %>

app/views/planner_notes/new.html.erb
<h1>New planner note</h1>

<%= render "form", planner_note: @planner_note %>

<br>

<div>
  <%= link_to "Back to planner notes", planner_notes_path %>
</div>

app/views/planner_notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @planner_note %>

<div>
  <%= link_to "Edit this planner note", edit_planner_note_path(@planner_note) %> |
  <%= link_to "Back to planner notes", planner_notes_path %>

  <%= button_to "Destroy this planner note", @planner_note, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :id_number, style: "display: block" %>
    <%= form.text_field :id_number %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Student id:</strong>
    <%= student.id %>
  </p>
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>DNI:</strong>
    <%= student.id_number %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= student.date_of_birth %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= student.course_id %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>